@host=http://localhost:5015

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3YzZmYTRkMC1lNjc4LTQ2YWEtYTFlYi0xOTBmZDllZDAzMGEiLCJnaXZlbl9uYW1lIjoibiIsImZhbWlseV9uYW1lIjoic2RmIiwianRpIjoiYzIxN2VkYWItY2I0MC00ZTgyLThmYTctZDg2NGU4ODg5MDgzIiwiZXhwIjoxNjcwOTUzNTg2LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.Jrn36-8TK3I45VWDnf4gqkeMqXBMqMLhvvWISNcoCLE